version: '3'

services:
  web:
    image: johnbda99/john-web
    container_name: web-ph
    links:
      - "db:finals_default"
    depends_on:
      - db
    volumes:
      - ./var/www/html/
    ports:
       - "8000:80"
    stdin_open: true
    tty: true




  db:
    image: johnbda99/john-db
    container_name: timedb
    ports:
      - "3306:3306"

